export default [
  {
    "statements": [
      "CREATE TYPE task_status AS ENUM (\n 'to_do',\n 'in_progress',\n 'completed'\n)",
      "CREATE TABLE tasks (\n    id uuid NOT NULL,\n    title text NOT NULL,\n    description text,\n    status task_status NOT NULL,\n    created_at timestamp with time zone NOT NULL,\n    updated_at timestamp with time zone NOT NULL,\n    CONSTRAINT tasks_pkey PRIMARY KEY (id)\n)",
      "INSERT INTO \"public\".\"_electric_trigger_settings\" (\"namespace\", \"tablename\", \"flag\")\n  VALUES ('public', 'tasks', 1)\n  ON CONFLICT DO NOTHING;",
      "DROP TRIGGER IF EXISTS update_ensure_public_tasks_primarykey ON \"public\".\"tasks\";",
      "CREATE OR REPLACE FUNCTION update_ensure_public_tasks_primarykey_function()\nRETURNS TRIGGER AS $$\nBEGIN\n  IF OLD.\"id\" IS DISTINCT FROM NEW.\"id\" THEN\n    RAISE EXCEPTION 'Cannot change the value of column id as it belongs to the primary key';\n  END IF;\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;",
      "CREATE TRIGGER update_ensure_public_tasks_primarykey\n  BEFORE UPDATE ON \"public\".\"tasks\"\n    FOR EACH ROW\n      EXECUTE FUNCTION update_ensure_public_tasks_primarykey_function();",
      "DROP TRIGGER IF EXISTS insert_public_tasks_into_oplog ON \"public\".\"tasks\";",
      "    CREATE OR REPLACE FUNCTION insert_public_tasks_into_oplog_function()\n    RETURNS TRIGGER AS $$\n    BEGIN\n      DECLARE\n        flag_value INTEGER;\n      BEGIN\n        -- Get the flag value from _electric_trigger_settings\n        SELECT flag INTO flag_value FROM \"public\"._electric_trigger_settings WHERE namespace = 'public' AND tablename = 'tasks';\n\n        IF flag_value = 1 THEN\n          -- Insert into _electric_oplog\n          INSERT INTO \"public\"._electric_oplog (namespace, tablename, optype, \"primaryKey\", \"newRow\", \"oldRow\", timestamp)\n          VALUES (\n            'public',\n            'tasks',\n            'INSERT',\n            json_strip_nulls(json_build_object('id', new.\"id\")),\n            jsonb_build_object('created_at', new.\"created_at\", 'description', new.\"description\", 'id', new.\"id\", 'status', new.\"status\", 'title', new.\"title\", 'updated_at', new.\"updated_at\"),\n            NULL,\n            NULL\n          );\n        END IF;\n\n        RETURN NEW;\n      END;\n    END;\n    $$ LANGUAGE plpgsql;",
      "CREATE TRIGGER insert_public_tasks_into_oplog\n  AFTER INSERT ON \"public\".\"tasks\"\n    FOR EACH ROW\n      EXECUTE FUNCTION insert_public_tasks_into_oplog_function();",
      "DROP TRIGGER IF EXISTS update_public_tasks_into_oplog ON \"public\".\"tasks\";",
      "    CREATE OR REPLACE FUNCTION update_public_tasks_into_oplog_function()\n    RETURNS TRIGGER AS $$\n    BEGIN\n      DECLARE\n        flag_value INTEGER;\n      BEGIN\n        -- Get the flag value from _electric_trigger_settings\n        SELECT flag INTO flag_value FROM \"public\"._electric_trigger_settings WHERE namespace = 'public' AND tablename = 'tasks';\n\n        IF flag_value = 1 THEN\n          -- Insert into _electric_oplog\n          INSERT INTO \"public\"._electric_oplog (namespace, tablename, optype, \"primaryKey\", \"newRow\", \"oldRow\", timestamp)\n          VALUES (\n            'public',\n            'tasks',\n            'UPDATE',\n            json_strip_nulls(json_build_object('id', new.\"id\")),\n            jsonb_build_object('created_at', new.\"created_at\", 'description', new.\"description\", 'id', new.\"id\", 'status', new.\"status\", 'title', new.\"title\", 'updated_at', new.\"updated_at\"),\n            jsonb_build_object('created_at', old.\"created_at\", 'description', old.\"description\", 'id', old.\"id\", 'status', old.\"status\", 'title', old.\"title\", 'updated_at', old.\"updated_at\"),\n            NULL\n          );\n        END IF;\n\n        RETURN NEW;\n      END;\n    END;\n    $$ LANGUAGE plpgsql;",
      "CREATE TRIGGER update_public_tasks_into_oplog\n  AFTER UPDATE ON \"public\".\"tasks\"\n    FOR EACH ROW\n      EXECUTE FUNCTION update_public_tasks_into_oplog_function();",
      "DROP TRIGGER IF EXISTS delete_public_tasks_into_oplog ON \"public\".\"tasks\";",
      "    CREATE OR REPLACE FUNCTION delete_public_tasks_into_oplog_function()\n    RETURNS TRIGGER AS $$\n    BEGIN\n      DECLARE\n        flag_value INTEGER;\n      BEGIN\n        -- Get the flag value from _electric_trigger_settings\n        SELECT flag INTO flag_value FROM \"public\"._electric_trigger_settings WHERE namespace = 'public' AND tablename = 'tasks';\n\n        IF flag_value = 1 THEN\n          -- Insert into _electric_oplog\n          INSERT INTO \"public\"._electric_oplog (namespace, tablename, optype, \"primaryKey\", \"newRow\", \"oldRow\", timestamp)\n          VALUES (\n            'public',\n            'tasks',\n            'DELETE',\n            json_strip_nulls(json_build_object('id', old.\"id\")),\n            NULL,\n            jsonb_build_object('created_at', old.\"created_at\", 'description', old.\"description\", 'id', old.\"id\", 'status', old.\"status\", 'title', old.\"title\", 'updated_at', old.\"updated_at\"),\n            NULL\n          );\n        END IF;\n\n        RETURN NEW;\n      END;\n    END;\n    $$ LANGUAGE plpgsql;",
      "CREATE TRIGGER delete_public_tasks_into_oplog\n  AFTER DELETE ON \"public\".\"tasks\"\n    FOR EACH ROW\n      EXECUTE FUNCTION delete_public_tasks_into_oplog_function();"
    ],
    "version": "1"
  },
  {
    "statements": [
      "ALTER TABLE tasks ADD COLUMN due_date TIMESTAMPTZ",
      "INSERT INTO \"public\".\"_electric_trigger_settings\" (\"namespace\", \"tablename\", \"flag\")\n  VALUES ('public', 'tasks', 1)\n  ON CONFLICT DO NOTHING;",
      "DROP TRIGGER IF EXISTS update_ensure_public_tasks_primarykey ON \"public\".\"tasks\";",
      "CREATE OR REPLACE FUNCTION update_ensure_public_tasks_primarykey_function()\nRETURNS TRIGGER AS $$\nBEGIN\n  IF OLD.\"id\" IS DISTINCT FROM NEW.\"id\" THEN\n    RAISE EXCEPTION 'Cannot change the value of column id as it belongs to the primary key';\n  END IF;\n  RETURN NEW;\nEND;\n$$ LANGUAGE plpgsql;",
      "CREATE TRIGGER update_ensure_public_tasks_primarykey\n  BEFORE UPDATE ON \"public\".\"tasks\"\n    FOR EACH ROW\n      EXECUTE FUNCTION update_ensure_public_tasks_primarykey_function();",
      "DROP TRIGGER IF EXISTS insert_public_tasks_into_oplog ON \"public\".\"tasks\";",
      "    CREATE OR REPLACE FUNCTION insert_public_tasks_into_oplog_function()\n    RETURNS TRIGGER AS $$\n    BEGIN\n      DECLARE\n        flag_value INTEGER;\n      BEGIN\n        -- Get the flag value from _electric_trigger_settings\n        SELECT flag INTO flag_value FROM \"public\"._electric_trigger_settings WHERE namespace = 'public' AND tablename = 'tasks';\n\n        IF flag_value = 1 THEN\n          -- Insert into _electric_oplog\n          INSERT INTO \"public\"._electric_oplog (namespace, tablename, optype, \"primaryKey\", \"newRow\", \"oldRow\", timestamp)\n          VALUES (\n            'public',\n            'tasks',\n            'INSERT',\n            json_strip_nulls(json_build_object('id', new.\"id\")),\n            jsonb_build_object('created_at', new.\"created_at\", 'description', new.\"description\", 'due_date', new.\"due_date\", 'id', new.\"id\", 'status', new.\"status\", 'title', new.\"title\", 'updated_at', new.\"updated_at\"),\n            NULL,\n            NULL\n          );\n        END IF;\n\n        RETURN NEW;\n      END;\n    END;\n    $$ LANGUAGE plpgsql;",
      "CREATE TRIGGER insert_public_tasks_into_oplog\n  AFTER INSERT ON \"public\".\"tasks\"\n    FOR EACH ROW\n      EXECUTE FUNCTION insert_public_tasks_into_oplog_function();",
      "DROP TRIGGER IF EXISTS update_public_tasks_into_oplog ON \"public\".\"tasks\";",
      "    CREATE OR REPLACE FUNCTION update_public_tasks_into_oplog_function()\n    RETURNS TRIGGER AS $$\n    BEGIN\n      DECLARE\n        flag_value INTEGER;\n      BEGIN\n        -- Get the flag value from _electric_trigger_settings\n        SELECT flag INTO flag_value FROM \"public\"._electric_trigger_settings WHERE namespace = 'public' AND tablename = 'tasks';\n\n        IF flag_value = 1 THEN\n          -- Insert into _electric_oplog\n          INSERT INTO \"public\"._electric_oplog (namespace, tablename, optype, \"primaryKey\", \"newRow\", \"oldRow\", timestamp)\n          VALUES (\n            'public',\n            'tasks',\n            'UPDATE',\n            json_strip_nulls(json_build_object('id', new.\"id\")),\n            jsonb_build_object('created_at', new.\"created_at\", 'description', new.\"description\", 'due_date', new.\"due_date\", 'id', new.\"id\", 'status', new.\"status\", 'title', new.\"title\", 'updated_at', new.\"updated_at\"),\n            jsonb_build_object('created_at', old.\"created_at\", 'description', old.\"description\", 'due_date', old.\"due_date\", 'id', old.\"id\", 'status', old.\"status\", 'title', old.\"title\", 'updated_at', old.\"updated_at\"),\n            NULL\n          );\n        END IF;\n\n        RETURN NEW;\n      END;\n    END;\n    $$ LANGUAGE plpgsql;",
      "CREATE TRIGGER update_public_tasks_into_oplog\n  AFTER UPDATE ON \"public\".\"tasks\"\n    FOR EACH ROW\n      EXECUTE FUNCTION update_public_tasks_into_oplog_function();",
      "DROP TRIGGER IF EXISTS delete_public_tasks_into_oplog ON \"public\".\"tasks\";",
      "    CREATE OR REPLACE FUNCTION delete_public_tasks_into_oplog_function()\n    RETURNS TRIGGER AS $$\n    BEGIN\n      DECLARE\n        flag_value INTEGER;\n      BEGIN\n        -- Get the flag value from _electric_trigger_settings\n        SELECT flag INTO flag_value FROM \"public\"._electric_trigger_settings WHERE namespace = 'public' AND tablename = 'tasks';\n\n        IF flag_value = 1 THEN\n          -- Insert into _electric_oplog\n          INSERT INTO \"public\"._electric_oplog (namespace, tablename, optype, \"primaryKey\", \"newRow\", \"oldRow\", timestamp)\n          VALUES (\n            'public',\n            'tasks',\n            'DELETE',\n            json_strip_nulls(json_build_object('id', old.\"id\")),\n            NULL,\n            jsonb_build_object('created_at', old.\"created_at\", 'description', old.\"description\", 'due_date', old.\"due_date\", 'id', old.\"id\", 'status', old.\"status\", 'title', old.\"title\", 'updated_at', old.\"updated_at\"),\n            NULL\n          );\n        END IF;\n\n        RETURN NEW;\n      END;\n    END;\n    $$ LANGUAGE plpgsql;",
      "CREATE TRIGGER delete_public_tasks_into_oplog\n  AFTER DELETE ON \"public\".\"tasks\"\n    FOR EACH ROW\n      EXECUTE FUNCTION delete_public_tasks_into_oplog_function();"
    ],
    "version": "2"
  }
]